language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.5"
  - "3.6"
install:
  - pip install numpy && python ./setup.py install
matrix:
  include:
    - python: 3.7
      dist: xenial
script: nosetests -sv
