on: pull_request
jobs:
  testLinux:
    name: TestLinux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo
          environment-file: .environmentLinux.yaml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          pip install .
          nosetests -sv
